[package]
name = "AdventOfCode2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
once_cell = "1.19.0"
strum = "0.25"
strum_macros = "0.25"
